dubbo:
  application:
    name: ${spring.application.name}
  registry:
#    address: nacos://127.0.0.1:8848?username=nacos&password=nacos&&namespace=test
    address: zookeeper://127.0.0.1:2181
    username: nacos
    password: nacos
#    group: test
#    parameters:
#      group: test
#      namespace: test
  consumer:
    timeout: 4000
    check: true
  protocol:
    port: 10080
    name: tri
    serialization: protobuf

spring:
  application:
    name: test-dubbo-consumer
