dubbo:
  scan:
    base-packages: com.test.dubbo.impl
  registry:
    address: nacos://127.0.0.1:8848?username=nacos&password=nacos&namespace=test
    use-as-metadata-center: false
#    use-as-config-center: false
    username: nacos
    password: nacos
    group: test
    parameters:
      group: test
      namespace: test
      username: nacos
      password: nacos
  protocol:
    port: 20880
    name: tri

spring:
  application:
    name: test-dubbo-provider
server:
  port: 8081
